# Generated by Django 2.1.4 on 2019-02-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meetingttitle',
            new_name='meetingtitle',
        ),
    ]
